# the debug level dictates what is printed to console
#   0: No printing
#   1: Errors/Info
#   2: Warnings (Suggested)
#   3: Debug
Debug_Level: 2
Print_Traces: false

# Automatically download WeaponMechanics when not already installed.
Weapon_Mechanics_Download:
  Enabled: true
  Connection_Timeout: 10
  Read_Timeout: 30